### PR TITLE
Fix clean_working_directory and never_cleaup_artifacts boolean properties on pipeline stages

### LINKED ISSUE #67: Missing boolean properties on created pipeline stages
@moritzheiber Reports that `clean_working_directory` and `fetch_materials` are not being applied correctly to Pipeline Stages.

Initial investigation shows that `never_cleanup_artifacts` isn't being applied either.

### PR DESCRIPTION
**Pull request by ixalon**
## Description
Adds tests for the 3 boolean properties on pipeline stages and verifies they are set in GoCD (by querying the template back via the API).

## Related Issue
Fixes #67

## Motivation and Context
Boolean properties were not being correctly set.

## How Has This Been Tested?
See test changes in this PR.

### CODE REVIEW

**Comment by ixalon** [comment]
Give the test:
```provider "gocd" {
  baseurl        = "http://localhost:8153/go/"
  skip_ssl_check = true
}

resource "gocd_pipeline" "pipeline" {
  name           = "Build"
  group          = "Test"
  label_template = "$${COUNT}"

  materials = [
    {
      type = "git"

      attributes {
        name = "git"
        url  = "git@url.local"
      }
    },
  ]
}

resource "gocd_pipeline_stage" "stage" {
  name     = "build"
  pipeline = "${gocd_pipeline.pipeline.name}"

  fetch_materials         = false

  jobs = [
    "${data.gocd_job_definition.job.json}",
  ]
}

data "gocd_job_definition" "job" {
  name = "docker_test"

  tasks = [
    "${data.gocd_task_definition.task.json}",
  ]
}

data "gocd_task_definition" "task" {
  type    = "exec"
  command = "/bin/bash"

  arguments = [
    "-c",
    "echo Hello World!"
  ]
}```

Applying to a pipeline with `fetch_materials = true` would give a permadiff:

```chris:test chris$ terraform apply
gocd_pipeline.pipeline: Refreshing state... (ID: Build)
data.gocd_task_definition.task: Refreshing state...
data.gocd_job_definition.job: Refreshing state...
gocd_pipeline_stage.stage: Refreshing state... (ID: pipeline/Build/build)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ gocd_pipeline_stage.stage
      fetch_materials: "true" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

gocd_pipeline_stage.stage: Modifying... (ID: pipeline/Build/build)
  fetch_materials: "true" => "false"
gocd_pipeline_stage.stage: Modifications complete after 0s (ID: pipeline/Build/build)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
chris:test chris$ terraform apply
gocd_pipeline.pipeline: Refreshing state... (ID: Build)
data.gocd_task_definition.task: Refreshing state...
data.gocd_job_definition.job: Refreshing state...
gocd_pipeline_stage.stage: Refreshing state... (ID: pipeline/Build/build)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ gocd_pipeline_stage.stage
      fetch_materials: "true" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

gocd_pipeline_stage.stage: Modifying... (ID: pipeline/Build/build)
  fetch_materials: "true" => "false"
gocd_pipeline_stage.stage: Modifications complete after 1s (ID: pipeline/Build/build)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
chris:test chris$ terraform apply
gocd_pipeline.pipeline: Refreshing state... (ID: Build)
data.gocd_task_definition.task: Refreshing state...
data.gocd_job_definition.job: Refreshing state...
gocd_pipeline_stage.stage: Refreshing state... (ID: pipeline/Build/build)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ gocd_pipeline_stage.stage
      fetch_materials: "true" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

gocd_pipeline_stage.stage: Modifying... (ID: pipeline/Build/build)
  fetch_materials: "true" => "false"
gocd_pipeline_stage.stage: Modifications complete after 0s (ID: pipeline/Build/build)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

With this fix:
```
chris:test chris$ terraform apply
gocd_pipeline.pipeline: Refreshing state... (ID: Build)
data.gocd_task_definition.task: Refreshing state...
data.gocd_job_definition.job: Refreshing state...
gocd_pipeline_stage.stage: Refreshing state... (ID: pipeline/Build/build)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ gocd_pipeline_stage.stage
      fetch_materials: "true" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

gocd_pipeline_stage.stage: Modifying... (ID: pipeline/Build/build)
  fetch_materials: "true" => "false"
gocd_pipeline_stage.stage: Modifications complete after 1s (ID: pipeline/Build/build)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
chris:test chris$ terraform apply
gocd_pipeline.pipeline: Refreshing state... (ID: Build)
data.gocd_task_definition.task: Refreshing state...
data.gocd_job_definition.job: Refreshing state...
gocd_pipeline_stage.stage: Refreshing state... (ID: pipeline/Build/build)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

File: gocd/resource_pipeline_stage_test.go [hunk 1]
```diff
@@ -120,12 +204,32 @@ func testCheckPipelineStageExists(resource string) r.TestCheckFunc {
 			return fmt.Errorf("No pipeline stage name is set")
 		}
 
+		cfg := gocd.Configuration{
```
Comment (drewsonne) [inline gocd/resource_pipeline_stage_test.go]: Could this be moved to provider_test.go and put in the module scope, as say... testClient, so other things can access it, rather than re-initing the client for each time we want to do this kind of test.

File: gocd/resource_pipeline_stage_test.go [hunk 2]
```diff
@@ -120,12 +204,32 @@ func testCheckPipelineStageExists(resource string) r.TestCheckFunc {
...
+			Server:   os.Getenv("GOCD_URL"),
+			Username: os.Getenv("GOCD_USERNAME"),
+			Password: os.Getenv("GOCD_PASSWORD"),
+		}
+
+		c := cfg.Client()
+		p, _, _ := c.PipelineTemplates.Get(context.Background(), "test-pipeline-template")
```
Comment (drewsonne) [inline gocd/resource_pipeline_stage_test.go]: This should test the error and return it, if we get an error rather than swallowing the error.

**Comment by drewsonne** [comment]
wasn't thinking when I approved. just had a couple of questions and comments

**Comment by ixalon** [comment]
@drewsonne Fixed
